development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: rails-links_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: rails-links_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  