# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f052fc68538cd38a6759943fd4f83af7b0f552496fd0331d4251ca77bd1b71c29739708193f7c3ca2559c30781719c9240004f662301a32eec85b00db8837ef4

test:
  secret_key_base: 5c8f1db11ba97da47c764e23c62287c4b6f74048f6fc6db0dfc14fc191e8858189a0f201b00a771b509d8177cef2109d07fd791d91131c9beb93c04216e4396b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
